#!/usr/bin/env python

import sys
import reading_files as rf
import generating_matrix as gm
import efficient_plotting as ep
import plotting_dotplot as dp
from efficient_plotting import ARGS as args


def main(argv):
    """
    main function which produces dotplot
    using other functions to do each
    individual task
    """
    seq1_ids, seq1 = rf.parse_fasta_file(args.seq1)
    seq2_ids, seq2 = rf.parse_fasta_file(args.seq2)
    seq1 = rf.fixing_sequence(seq1)
    seq2 = rf.fixing_sequence(seq2)
    matrix = gm.creating_matrix(seq1, seq2)
    print_matrix = ep.prepare_filtering(matrix, seq1, seq2)
    dp.plotting(print_matrix, seq1, seq2)


main(sys.argv)
