import sys


def lines_from_file(filename):
    '''opens file and reads contents into a list'''
    try:
        with open(filename) as file_in:
            contents = file_in.read()
            lines = contents.splitlines()
    except FileNotFoundError:
        print('Unable to read file')
        sys.exit(1)
    else:
        return lines


def parse_fasta_from_lines(lines):
    '''splits fasta format into IDs and sequences'''
    ids = []
    seq = []
    joined_seq = []
    for fasta in lines:
        if fasta[0] == '>':
            fasta = fasta.replace('>', '')
            ids.append(fasta)
            if len(seq) != 0:
                joins = "".join(seq)
                joined_seq.append(joins)
                seq = []
        else:
            seq.append(fasta)
    joins = "".join(seq)
    joined_seq.append(joins)
    seq = []
    return ids, joined_seq


def parse_fasta_file(filename):
    '''reads in fasta file and splits into IDs and sequence'''
    lines = lines_from_file(filename)
    ids, joined_seq = parse_fasta_from_lines(lines)
    return ids, joined_seq


def fixing_sequence(seq):
    '''
    removes unneccessary characters
    from list generated by reading
    in files
    '''
    seq = str(seq).strip("[]")
    seq = seq.strip("'")
    seq = seq.upper()
    return seq
